# -*- coding: utf-8 -*-
"""ma_desencriptado.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6JPcFWsiEFfuVH7_UObdzwt68YYM1u9
"""

import pandas as pd
import numpy as np

fileMA=open('cifradoMA.txt', mode='r', encoding="unicode-escape")
mensaje = fileMA.read()
print(mensaje)
fileMA.close()

n_char = np.arange(256)
c_zero = np.zeros(256)
diccionario_char = {n_char:c_zero for(n_char,c_zero) in zip(n_char,c_zero)}

for c in mensaje:
    diccionario_char[ord(c)] = diccionario_char[ord(c)]+1

columns=['Cod', 'Count']
df = pd.DataFrame([[key, diccionario_char[key]] for key in diccionario_char.keys()], columns=columns)
df = df.drop(df[df['Count']==0].index)
df = df.sort_values('Cod', ascending=False)
df

copy_message = mensaje

copy_message = copy_message.replace(chr(142),' ') #ok
copy_message = copy_message.replace(chr(68),';') #ok
copy_message = copy_message.replace(chr(10),',') #ok
copy_message = copy_message.replace(chr(184),'L') #ok
copy_message = copy_message.replace(chr(11),'.') #ok
copy_message = copy_message.replace(chr(29),':') #ok

copy_message = copy_message.replace(chr(114),'b')   # r => b 
copy_message = copy_message.replace(chr(113),'{')   # q => 
copy_message = copy_message.replace(chr(97),'/')    # a => 
copy_message = copy_message.replace(chr(85),'d')    # U => 
copy_message = copy_message.replace(chr(83),'y')    # S => 
copy_message = copy_message.replace(chr(68),']')    # D => 


copy_message = copy_message.replace(chr(191),'a') #ok
copy_message = copy_message.replace(chr(6),'e')   #ok
copy_message = copy_message.replace(chr(44),'o')
copy_message = copy_message.replace(chr(214),'r') #ok
copy_message = copy_message.replace(chr(129),'s') #ok
copy_message = copy_message.replace(chr(31),'n')
copy_message = copy_message.replace(chr(138),'l') #ok
copy_message = copy_message.replace(chr(33),'d') #ok
copy_message = copy_message.replace(chr(83),'y') #ok 




copy_message = copy_message.replace(chr(38),'c')
copy_message = copy_message.replace(chr(252),'i')
copy_message = copy_message.replace(chr(21),'f')
copy_message = copy_message.replace(chr(35),'g')
copy_message = copy_message.replace('','h')
copy_message = copy_message.replace(chr(27),'m')
copy_message = copy_message.replace(chr(17),'p')
copy_message = copy_message.replace(chr(24),'q')
copy_message = copy_message.replace(chr(55),'j')
copy_message = copy_message.replace(chr(220),'u')
copy_message = copy_message.replace(chr(186),'v')
copy_message = copy_message.replace(chr(5),'z')

copy_message = copy_message.replace('ðú','ó')
copy_message = copy_message.replace('ð`','é')
copy_message = copy_message.replace('ð','í')
copy_message = copy_message.replace('ð/','ú')
copy_message = copy_message.replace('ð','ñ')
copy_message = copy_message.replace('ò','\n')
copy_message = copy_message.replace('ð{','á')
copy_message = copy_message.replace(chr(196),'A')
copy_message = copy_message.replace(chr(16),'E')
copy_message = copy_message.replace("'",'C')
copy_message = copy_message.replace(chr(249),'M')
copy_message = copy_message.replace(chr(224),'P')
copy_message = copy_message.replace(chr(226),'S')
copy_message = copy_message.replace(chr(219),'T')
copy_message = copy_message.replace("*",'V')


inicio = 2000
fin = len(mensaje)
print(copy_message)